### PR TITLE
Fixes up mext protocol

### PR DESCRIPTION
**Pull request by amj**
howdy!  here's a PR that might get things moving.  Basically, i fixed up some of the commands that bailed out early and would've left bytes left in the serial queue.

So far, this 'works ish'.  I can get some patches to work, but once there's a lot of messages flying, the poor arduino i was using can't keep up.  It's a 2009-era atmega1280, so my guess is it could probably be faster...

Anyway, next step is to optimize and try and figure out the ideal delay values -- these still have some trouble with debouncing.  I'm not sure if the different trellisxy library used [here](https://github.com/rbnstubbs/trellis-monome) is more efficient or not, but it might be worth investigating.

### CODE REVIEW

**Comment by TheKitty** [comment]
Nice work, I have merged your PR in. The processor I was using for the Untz
is an ATmega 32u4. Adafruit chose it for projects at the time as it was the
first to have the USB on chip. Alot of 32u4 alternatives have come out.
With Untz multiplexing, not many pins are needed. I think a more modern
processor, maybe Teensy, might be able to handle more work?

**Comment by brianlight** [comment]
I have a Teensy 3.1 in my Untz and this Sketch compiles fine under the Teensyduino IDE but SerialOSC does not detect my Untz as a Monome device :-( any pointers on how to make that happen? I'm not sure if you can flash FTDI EEPROM in the  same way as the ReadMe states I did not want to try yet, because I don't want to risk damaging the firmware on my teensy until I know the best route to go.

**Comment by TheKitty** [comment]
I have not worked much at all with Teensy, it may not allow for outputting
a different pid/vid IDs for USB.

For Teensy, perhaps their forum members could answer (they have a very
active forum).

Or else find another processor more fitting. . .

On Wed, Oct 12, 2016 at 4:57 PM, Brian R Lightfoot <notifications@github.com

**Comment by brianlight** [comment]
It looks like someone has asked this question before..,  I came across this forum post that seems to have the information on how to do this with Teensy @ https://forum.pjrc.com/archive/index.php/t-23796.html

I think I've attempted this in the past and was frustrated I'm thinking I was doing the right things but possibly windows cached the vid/pid for the usb device?

I'll attempt to change the USB vid/pid again using the information & test in Linux See If i cant get the teensy hardware to show up for Serialosc to use with all that awesome Monome stuff out there. 

From the demo sketches that are available for the UNTZ it does seem to run the sketches smoother and it's easier overall easier to use with MIDI USB

**Comment by amj** [comment]
Brianlight: serialosc detection seems to rely on the pid/vid info to be correct.  Not sure if piraterename works w/ teensy, but i have one showing up here today (coincidentally) so i can give it a shot!

TheKitty: Thanks for merging!  It might be easier to check the libraries before switching chipsets ;)  I will admit that a lot of that lower level 'turn off unneeded clocks' stuff happening on https://github.com/rbnstubbs/trellis-monome is totally opaque to me.

**Comment by TheKitty** [comment]
I have to be perfectly honest that there are some layers of getting from
the hardware to the PC that are fuzzy to me, but I'm more of a programmer
and not a musician.

I'd just be happy to see the Untz actually looking like it's working like a
monome device and for the community to be happy too. You've definitely
helped push the car out of the ditch.

**Comment by brianlight** [comment]
I tried last night to resolve my issues with SerialOSC following that forum post about changing USB PID/VID but was unable to make any headway. Did you have any luck amj? It also appears that the teensy 3.1 does that have FTDI chip.

**Pull request merged**
